name: Functional tests using Ragger

on:
  workflow_call:
    inputs:
      app_repository:
        description: 'The GIT repository to test (defaults to `github.repository`)'
        required: false
        default: ${{ github.repository }}
        type: string
      app_branch_name:
        description: 'The GIT branch to test (defaults to `github.ref`)'
        required: false
        default: ${{ github.ref }}
        type: string
      relative_app_directory:
        description: 'The relative path in the repository where the application is built from (defaults to ".")'
        required: false
        default: .
        type: string
      test_dir:
        description: 'The directory where the Python tests are stored (a `conftest.py` file is expected there). Required'
        required: true
        type: string
      download_app_binaries_artifact:
        description: 'The name of the artifact containing the application binary file(s) to be tested. Required'
        required: true
        type: string
      lib_binaries_artifact:
        description: 'The name of the artifact containing the library binary file(s), if needed by the application to be tested (defaults to empty string)'
        required: false
        default: ''
        type: string
      run_for_devices:
        description: 'The list of device(s) on which the test will run (defaults to ["nanos", "nanox", "nanosp", "stax"])'
        required: false
        default: '["nanos", "nanox", "nanosp", "stax"]'
        type: string
      upload_snapshots_on_failure:
        description: 'Enable or disable upload of tests snapshots if the job fails (defaults to true).'
        required: false
        default: true
        type: boolean

jobs:
  ragger_tests:
    name: Functional tests with Ragger
    strategy:
      fail-fast: false
      matrix:
        device: ${{ fromJSON(inputs.run_for_devices) }}
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.app_repository }}
          ref: ${{ inputs.app_branch_name }}
          submodules: recursive

      - name: Download app binaries
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.download_app_binaries_artifact }}
          path: ${{ inputs.relative_app_directory }}/build/

      - name: Download additional lib binaries if required
        if: ${{ inputs.lib_binaries_artifact != '' }}
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.lib_binaries_artifact }}
          path: ${{ inputs.test_dir }}/lib_binaries/

      - name: Install tests dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y qemu-user-static tesseract-ocr libtesseract-dev
          pip install --extra-index-url https://test.pypi.org/simple/ -r ${{ inputs.test_dir }}/requirements.txt
      - name: Run test
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
        run: pytest ${{ inputs.test_dir }}/ --tb=short -v --device ${{ matrix.device }}

      - name: Upload snapshots
        if: ${{ failure() && inputs.upload_snapshots_on_failure == true }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.device }}-tests-snapshots
          path: ${{ inputs.test_dir }}/snapshots-tmp/${{ matrix.device }}

